---
title: "Anexos Docker"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
lightbox: true
---

## Anexo

Código para generar los archivos .geojson que alimentan la app.R

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "../")
getwd()

```

```{r}
#| eval: false
#| include: true
## Se leen las geometrías de los AGEBS: 
library(sf)
library(raster)
demograficos_scince=st_read("outputs/demograficos_cartograficos_scince_20.geojson")
##Este se construye con el marco Geoestadístico de INEGI, se le aplica un buffer a las localidades rurales de tipo punto y se hace una simplificación de geometrías para reducir el tamaño (MB) del .geojson
##Se leen los CLUES
source("codigos/csv_to_geojson.R")
#
local <- DBI::dbConnect(RSQLite::SQLite(), tempfile("clues_en_operacion.sqlite"))

st_write(clues_en_operacion_s, local, "clues_en_operacion", delete_layer = FALSE)
clues_en_operacion=dplyr::tbl(local,"clues_en_operacion")

##Definimos los rasters de accesibilidad
#Solo necesitamos las ubicaciones de los CLUES clasificados por nivel y me genera los rasters a cada tipo de atención (1,2,3, _)
source("codigos/no_usar_calculos_rasters_accesibilidad.R")

source("codigos/no_usar_conteo_cluesN1_por_rangos_tiempo.R")

'source("codigos/no_usar_conteo_cluesN1_por_rangos_tiempo.R") 
   median       uq      max neval
 23842.38 23842.38 23842.38     1'

source("codigos/no_usar_calculos_accesibilidad_clues.R")

```



Se incorporan los cálculos generados en archivos .geojson

```{r}
#| eval: false
#| include: true
#inputs
demograficos_scince=sf::st_read("outputs/demograficos_cartograficos_scince_20.geojson")
clues_en_operacion_s=sf::st_read("outputs/clues_en_operacion.geojson") |> dplyr::arrange(NIVEL.ATENCION)

#outputs
demograficos_info_accesibilidad_clues=sf::st_read("outputs/demograficos_info_accesibilidad_clues.geojson")

aportaciones_de_ageb_por_clues=read.csv("outputs/aportaciones_de_ageb_por_clues.csv")
metricas_clues=read.csv("outputs/metricas_clues.csv")
conteo_por_nivel_de_atencion=clues_en_operacion_s |> sf::st_drop_geometry()|> dplyr::group_by(NIVEL.ATENCION) |> dplyr::summarise(conteo=dplyr::n())
#union
n1=conteo_por_nivel_de_atencion$conteo[1]
n2=conteo_por_nivel_de_atencion$conteo[2]
n3=conteo_por_nivel_de_atencion$conteo[3]

demograficos_info_accesibilidad_clues=demograficos_info_accesibilidad_clues |> 
  dplyr::mutate(
    id_clues_N1_mas_cercano=metricas_clues$CLUES[as.numeric(id_clues_N1_mas_cercano)]
    ) |> 
  dplyr::mutate(
    id_clues_N2_mas_cercano=metricas_clues$CLUES[(as.numeric(id_clues_N2_mas_cercano)+n1)]) |> 
  dplyr::mutate(
    id_clues_N3_mas_cercano=metricas_clues$CLUES[(as.numeric(id_clues_N3_mas_cercano)+n1+n2)]
                )

nombres_clues=clues_en_operacion_s |> 
  sf::st_drop_geometry() |> 
  dplyr::select(CLUES, NOMBRE.DE.LA.UNIDAD)

demograficos_info_accesibilidad_clues = demograficos_info_accesibilidad_clues |>
  dplyr::left_join(nombres_clues, by = c("id_clues_N1_mas_cercano" = "CLUES")) |>
  dplyr::rename(nombre_clues_N1_mas_cercano = NOMBRE.DE.LA.UNIDAD) |>
  dplyr::relocate(nombre_clues_N1_mas_cercano, .after = id_clues_N1_mas_cercano) |>
  
  # --- Nivel 2 ---
  dplyr::left_join(nombres_clues, by = c("id_clues_N2_mas_cercano" = "CLUES")) |>
  dplyr::rename(nombre_clues_N2_mas_cercano = NOMBRE.DE.LA.UNIDAD) |>
  dplyr::relocate(nombre_clues_N2_mas_cercano, .after = id_clues_N2_mas_cercano) |>
  
  # --- Nivel 3 ---
  dplyr::left_join(nombres_clues, by = c("id_clues_N3_mas_cercano" = "CLUES")) |>
  dplyr::rename(nombre_clues_N3_mas_cercano = NOMBRE.DE.LA.UNIDAD) |>
  dplyr::relocate(nombre_clues_N3_mas_cercano, .after = id_clues_N3_mas_cercano)



demograficos_info_accesibilidad_clues=demograficos_info_accesibilidad_clues |> dplyr::mutate(
    dplyr::across(c(CLUES_N1_10:CLUES_N1_60, 
             CLUES_N2_10:CLUES_N2_60, 
             CLUES_N3_10:CLUES_N3_60), as.numeric),
    
    dplyr::across(c(tiempo_promedio_clues_N1_mas_cercano, 
             tiempo_promedio_clues_N2_mas_cercano, 
             tiempo_promedio_clues_N3_mas_cercano), \(x) round(as.numeric(x), 2))
  )

clues_en_operacion_s=clues_en_operacion_s |> 
  merge(y=metricas_clues,by='CLUES')
clues_en_operacion_s=clues_en_operacion_s |> 
  merge(y=aportaciones_de_ageb_por_clues,by='CLUES')


#guardar
sf::st_write(clues_en_operacion_s,"outputs/clues_en_operacion_con_info_accesibilidad.geojson",driver='GeoJSON',append=F,delete_dsn = T)

sf::st_write(demograficos_info_accesibilidad_clues,"outputs/demograficos_con_info_accesibilidad.geojson",driver='GeoJSON',append=F,delete_dsn = T)


#guardar en un solo archivo 
limites_municipales=sf::st_read("inputs/accesibilidad_SIGEH/hidalgo/LIM_MUNICIPALES.shp") |> sf::st_transform(4326)
con <- DBI::dbConnect(RSQLite::SQLite(), "clues_demograficos_municipios.sqlite")

sf::st_write(clues_en_operacion_s, con, "clues_en_operacion", delete_layer = T)
sf::st_write(limites_municipales, con, "limite_municipal", delete_layer = T)
sf::st_write(demograficos_info_accesibilidad_clues , con, "demograficos_scince", delete_layer = T)


DBI::dbDisconnect(con)

```
