FROM rocker/r-ver:4.5.0
RUN apt-get update -y && apt-get install -y  make pandoc curl gdebi-core libpq-dev libcurl4-openssl-dev libssl-dev libicu-dev libxml2-dev libx11-dev git cmake libgdal-dev gdal-bin libgeos-dev libproj-dev libsqlite3-dev libudunits2-dev zlib1g-dev libglpk-dev libjq-dev libprotobuf-dev protobuf-compiler libprotoc-dev libpng-dev libsodium-dev && rm -rf /var/lib/apt/lists/*


RUN mkdir -p /usr/local/lib/R/etc/ /usr/lib/R/etc/
RUN echo "options(renv.config.pak.enabled = FALSE, repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl', Ncpus = 4)" | tee /usr/local/lib/R/etc/Rprofile.site | tee /usr/lib/R/etc/Rprofile.site
RUN R -e 'install.packages("remotes")'
RUN R -e 'remotes::install_version("renv", version = "1.0.3")'
COPY renv.lock renv.lock
RUN --mount=type=cache,id=renv-cache,target=/root/.cache/R/renv R -e 'renv::restore()'

RUN curl -LO https://quarto.org/download/latest/quarto-linux-amd64.deb
RUN gdebi --non-interactive quarto-linux-amd64.deb

WORKDIR /home/user/    
COPY . /home/user

RUN quarto render 'documentacion/Anexo_Docker.qmd'